name: Acceptance Tests

on:
  workflow_dispatch:
    name:
      description: 'Reason and Motivation for this run'
      required: true
      default: 'Because I think is important'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [11.0.x]
        go: ['^1.13.1']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: make testacc